#!/usr/bin/env bash
# Script that creates an RSA key pair. Name of the private key must be school. Number of bits 4096. The created key must be protected by the passphrase betty
ssh-keygen -t rsa -b 4096 -P 'betty' -f school
