#!/usr/bin/env bash
# Sets up nginx

sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start

echo "Holberton School" | sudo tee /var/www/html/index.html

sudo ufw allow 'Nginx HTTP'

sudo service nginx restart
